### ISSUE TITLE
Stackage release?

### ISSUE THREAD

**Issue by patrickt** [luke-clifton/generic-monoid#1]
This is a good and useful package that I’m using in production. Could it be added to a Stackage LTS release?

**Comment by Drezil** [comment]
I just used this package, but wanted to extend things more ..

Then i found http://hackage.haskell.org/package/generic-data and it is way more elaborated.
Maybe this helps some others struggeling with DerivingVia and looking for examples.

My code now looks:
```haskell
data Distance a = Distance
              { distX :: !a
              , distY :: !a
              , distZ :: !a
              , distW :: !a
              } deriving (Show, Generic, Functor, Eq, Ord, Generic1)
                deriving (Semigroup, Monoid) via Generically (Distance a)
                deriving (Applicative) via Generically1 Distance
                deriving Num via Ap Distance a --Num via Applicative ((+) = liftA2 (+) etc.)
```

So you need no seperate instances for Semigroup, Monoid, etc., but can just use Generically.

I think this package may be outdatad.

**Comment by luke-clifton** [comment]
Sorry for not getting to this, my GitHub notifications got broken and I didn't see it!

@patrickt I'll see about getting it into stackage. I'm not `stack` user myself, so my `stack` setup is currently broken to the point that I can't run the pre-stackage upload tests. I'll sort that out soon, then upload it.

@Drezil that is a nice package. I might add it to the readme of `generic-monoid`.

**Comment by patrickt** [comment]
@luke-clifton No worries! FWIW, in the months since, I’ve switched to `cabal new-build`, so I no longer have a pressing need, though it is a useful enough package that it deserves to be in Stackage.

**Comment by luke-clifton** [comment]
https://github.com/commercialhaskell/stackage/pull/4836

Better late than never.
