### ISSUE TITLE
Hackage revision for base 4.18 (GHC 9.4)

### ISSUE THREAD

**Issue by LaurentRDC** [luke-clifton/generic-monoid#4]
Hello,

Would it be possible to make a Hackage revision to loosen the bounds on `base` to include `base-4.18`? This would allow to build `generic-monoid` with GHC-9.4.

`generic-monoid` is the only package preventing me from compiling [`tmp-postgres`](https://hackage.haskell.org/package/tmp-postgres) using GHC 9.4.

Thank you!

**Comment by luke-clifton** [comment]
Done. Thanks for the reminder. I haven't even moved our production code-bases to GHC 9.x yet, so haven't needed it personally yet.

**Comment by LaurentRDC** [comment]
Thank you!
